const agentClass=name=>name==='Codex'?'codex':name==='Claude Code'?'claude':'opencode';
const originalRender=render;render=function(){originalRender();document.querySelectorAll('.row').forEach(row=>{const d=data[Number(row.dataset.id)];row.querySelector('.sender').innerHTML=`<span class="agent-name ${agentClass(d.agent)}"><i></i>${esc(d.agent)}</span>`})};
// Deliberately small Markdown renderer for this standalone design preview.
// Escape user text first; only generate supported formatting elements.
function inlineMd(text){return esc(text).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>')}
function markdown(text){let output='',code=false,lines=[],list=false;for(const line of text.split('\n')){if(line.startsWith('```')){if(list){output+='</ul>';list=false}if(code){output+='<pre><code>'+esc(lines.join('\n'))+'</code></pre>';lines=[]}code=!code;continue}if(code){lines.push(line);continue}if(/^[-*] /.test(line)){if(!list){output+='<ul>';list=true}output+='<li>'+inlineMd(line.slice(2))+'</li>';continue}if(list){output+='</ul>';list=false}if(/^###? /.test(line)){output+='<h3>'+inlineMd(line.replace(/^#+ /,''))+'</h3>'}else if(line.startsWith('> ')){output+='<blockquote>'+inlineMd(line.slice(2))+'</blockquote>'}else if(line.trim()){output+='<p>'+inlineMd(line)+'</p>'}}if(list)output+='</ul>';if(code)output+='<pre><code>'+esc(lines.join('\n'))+'</code></pre>';return output||'<p class="muted">Your Markdown preview will appear here.</p>'}
function editor(target){const area=$(target);if(area.parentElement.classList.contains('md-editor'))return;const wrapper=document.createElement('div');wrapper.className='md-editor';area.before(wrapper);wrapper.append(area);wrapper.insertAdjacentHTML('afterbegin',`<div class="editor-tools"><div class="format-group"><button type="button" data-format="bold" title="Bold" aria-label="Bold"><b>B</b></button><button type="button" data-format="italic" title="Italic" aria-label="Italic"><i>I</i></button><button type="button" data-format="heading" title="Heading" aria-label="Heading">H</button><button type="button" data-format="list" title="Bullet list" aria-label="Bullet list">☷</button><button type="button" data-format="code" title="Inline code" aria-label="Inline code">&lt;/&gt;</button></div><div class="preview-switch"><button type="button" class="chosen" data-editor-mode="write">Write</button><button type="button" data-editor-mode="preview">Preview</button></div></div>`);const preview=document.createElement('div');preview.className='markdown editor-preview';preview.hidden=true;wrapper.append(preview);wrapper.insertAdjacentHTML('beforeend','<div class="editor-hint">Markdown supported <span>Ctrl / ⌘ Enter to send</span></div>');wrapper.querySelectorAll('[data-format]').forEach(button=>button.onclick=()=>{const start=area.selectionStart,end=area.selectionEnd,value=area.value.slice(start,end);const format=button.dataset.format;const [before,after]=({bold:['**','**'],italic:['*','*'],heading:['## ',''],list:['- ',''],code:['`','`']})[format];area.setRangeText(before+(value||({bold:'bold text',italic:'italic text',heading:'Heading',list:'List item',code:'code'})[format])+after,start,end,'select');area.focus();area.dispatchEvent(new Event('input'))});wrapper.querySelectorAll('[data-editor-mode]').forEach(button=>button.onclick=()=>{const show=button.dataset.editorMode==='preview';preview.innerHTML=markdown(area.value);preview.hidden=!show;area.hidden=show;wrapper.querySelectorAll('[data-editor-mode]').forEach(b=>b.classList.toggle('chosen',b===button));if(!show)area.focus()});area.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();area.form.requestSubmit()}}}
let selectedMessage=0,currentChat=0;
const demoPrompts=['Please review the **navigation** and propose a simpler version.\n\n- Keep the project context visible\n- Make the main actions easy to find\n- Preserve keyboard navigation','This looks good. Could you make the **project tags** quieter and keep the agent easy to recognize?'];
function messageCard(d,author,text,time,index){const user=author==='You';return `<article class="conversation-message ${user?'from-you':'from-agent '+agentClass(d.agent)}" id="message-${index}" data-message="${index}"><div class="conversation-meta"><span class="speaker-avatar">${user?'Y':d.agent[0]}</span><strong>${user?'You':esc(d.agent)}</strong><span class="speaker-role">${user?'Prompt':'Response'}</span><time>${time}</time><button class="icon-button" type="button" data-copy="${index}" title="Copy Markdown" aria-label="Copy Markdown">⧉</button><button class="icon-button collapse-message" aria-expanded="true" aria-label="Collapse message">⌃</button></div><div class="markdown message-content">${markdown(text)}</div></article>`}
openMessage=function(i){currentChat=i;const d=data[i];d.unread=false;render();$('inbox').classList.add('hidden');$('reader').classList.add('open');$('back').hidden=false;$('select-all').hidden=true;selectedMessage=0;
const replies=[`## Navigation update\n\n${d.snippet}\n\nThe layout now has a **clearer hierarchy**. The repository stays visible, and the primary actions are easier to reach.\n\n- Simplified the sidebar\n- Preserved keyboard shortcuts\n- Checked the compact layout\n\n\`apps/web/src/components/Sidebar.tsx\``, 'Agreed. I softened the project tags and kept a small **agent color marker**.\n\n> Project context stays visible without competing with the conversation.\n\n```css\n.project-tag {\n  background: #f2f2ee;\n  border-radius: 4px;\n}\n```\n\nThe proposal is ready for your review.'];
const texts=[demoPrompts[0],replies[0],demoPrompts[1],replies[1]];
$('reader').innerHTML=`<div class="conversation-heading"><div><div class="breadcrumb">${esc(d.project)} <span>/</span> Conversation</div><h1>${esc(d.subject)}</h1></div><span class="terminal-state ${d.terminal}"><span class="state-dot"></span>Terminal ${d.terminal}</span></div><div class="git-context"><span class="context-path" title="${esc(d.path)}">▱ ${esc(d.path)}</span><button class="context-chip" id="git-branch" title="View session Git context">⑂ feature/navigation</button><button class="context-chip changes-chip" id="git-changes">2 changed files <span>+62 −28</span></button></div><div class="conversation-nav"><label class="conversation-search"><span>⌕</span><input id="conversation-search" placeholder="Find in conversation" aria-label="Find in conversation"></label><span id="find-count" aria-live="polite">4 messages</span><div class="conversation-navigation"><button class="icon-button" id="previous-message" title="Previous message" aria-label="Previous message">↑</button><button class="icon-button" id="next-message" title="Next message" aria-label="Next message">↓</button><button class="secondary-button" id="latest-message">Latest</button><button class="secondary-button" id="collapse-all">Collapse all</button><button class="secondary-button" id="focus-conversation" aria-pressed="false">Focus</button></div></div><div class="conversation-stream">${messageCard(d,'You',texts[0],'13:32',0)}${messageCard(d,d.agent,texts[1],'13:48',1)}${messageCard(d,'You',texts[2],'14:06',2)}${messageCard(d,d.agent,texts[3],d.time,3)}</div><form class="reply refined-reply" id="reply"><div class="reply-label"><label for="reply-text">Continue with <span class="agent-name ${agentClass(d.agent)}"><i></i>${esc(d.agent)}</span></label><span class="tag">${esc(d.project)}</span></div><textarea id="reply-text" placeholder="What should we work on next?" required></textarea><div class="reply-bottom"><small>Prompt preview · no agent connected</small><button class="send">Send prompt <span aria-hidden="true">↗</span></button></div></form>`;
editor('reply-text');$('reply').onsubmit=e=>{e.preventDefault();notify('Prompt preview · nothing sent')};
$('reader').querySelectorAll('.collapse-message').forEach(button=>button.onclick=()=>{const content=button.closest('article').querySelector('.message-content');content.hidden=!content.hidden;button.setAttribute('aria-expanded',!content.hidden);button.setAttribute('aria-label',content.hidden?'Expand message':'Collapse message');button.textContent=content.hidden?'⌄':'⌃'});
$('reader').querySelectorAll('[data-copy]').forEach(button=>button.onclick=async()=>{try{await navigator.clipboard.writeText(texts[Number(button.dataset.copy)]);notify('Markdown copied')}catch{notify('Clipboard unavailable in this preview')}});
function navigate(index){selectedMessage=(index+4)%4;const el=$('message-'+selectedMessage);el.querySelector('.message-content').hidden=false;const control=el.querySelector('.collapse-message');control.setAttribute('aria-expanded','true');control.textContent='⌃';el.scrollIntoView({behavior:'smooth',block:'center'});document.querySelectorAll('.conversation-message').forEach(card=>card.classList.toggle('current-message',card===el))}
$('previous-message').onclick=()=>navigate(selectedMessage-1);$('next-message').onclick=()=>navigate(selectedMessage+1);$('latest-message').onclick=()=>navigate(3);
$('collapse-all').onclick=e=>{const collapse=e.target.textContent==='Collapse all';document.querySelectorAll('.message-content').forEach(content=>content.hidden=collapse);document.querySelectorAll('.collapse-message').forEach(b=>{b.setAttribute('aria-expanded',!collapse);b.textContent=collapse?'⌄':'⌃'});e.target.textContent=collapse?'Expand all':'Collapse all'};
$('conversation-search').oninput=e=>{const q=e.target.value.trim().toLowerCase();let matches=[];document.querySelectorAll('.conversation-message').forEach((card,index)=>{const content=card.querySelector('.message-content');content.innerHTML=markdown(texts[index]);card.classList.remove('search-match');if(q&&content.textContent.toLowerCase().includes(q)){matches.push(index);card.classList.add('search-match');content.hidden=false}});$('find-count').textContent=q?matches.length+' matching messages':'4 messages';if(matches.length)navigate(matches[0])};
$('focus-conversation').onclick=e=>{const focus=document.body.classList.toggle('focus-reading');e.target.textContent=focus?'Exit focus':'Focus';e.target.setAttribute('aria-pressed',focus)};
$('git-branch').onclick=$('git-changes').onclick=()=>showGit(d);
};
function showGit(d){let panel=$('git-dialog');if(!panel){panel=document.createElement('dialog');panel.id='git-dialog';document.body.append(panel)}panel.innerHTML=`<div class="compose-head"><div><h2>Session Git context</h2><p>Local repository · ${esc(d.project)}</p></div><button class="icon-button" aria-label="Close Git context" onclick="document.getElementById('git-dialog').close()">×</button></div><div class="git-detail"><label>Working folder</label><code>${esc(d.path)}</code><label>Branch</label><div>⑂ feature/navigation <span class="tag">Shared folder</span></div><label>Working tree</label><div class="changed-file">Sidebar.tsx <span>+24 −12</span></div><div class="changed-file">workspace.css <span>+38 −16</span></div><p>These changes belong to the folder and may include edits from other sessions.</p></div><div class="git-suggestion"><strong>Suggested session setup</strong><p>Use the current branch for shared work, or choose a separate Git worktree when a session needs isolation.</p><button class="secondary-button" onclick="notify('Separate worktree — design preview only')">Explore a separate worktree</button></div><p class="field-help">Git context is illustrative. No repository operations are performed.</p>`;panel.showModal()}
const originalDestination=destination;destination=function(){originalDestination();const d=data[Number($('session-picker').value)];const chip=$('destination-card').querySelector('.agent-chip');chip.classList.add('agent-name',agentClass(d.agent));};
const originalBack=back;back=function(){document.body.classList.remove('focus-reading');originalBack()};$('back').onclick=back;
editor('prompt-body');render();
